# the column name of primary key in the table, default is `id`
PrimaryKey = "id"
# the column names for comparing differences, default are all columns in the table
DiffColumns = ["id", "col01", "col02"]

[Left]
    # the database source configuration
    DSN = "root:password@tcp(127.0.0.1:13306)/table_diff"
    # the table name for comparing differences
    Table = "table_diff_test"

[Right]
    # the database source configuration
    DSN = "root:password@tcp(127.0.0.1:13307)/table_diff"
    # the table name for comparing differences
    Table = "table_diff_test"

[Segment]
    # the min value of primary key in the comparing range, default is 0
    From = 0
    # the max value of primary key in the comparing range, default is the current max row id in the table
    To = 10000
    # the batch size in every segment, default is 1000
    Step = 10

[Filter]
    Where = ""

[Concurrency]
    # the size of the concurrently running worker, default is 1
    Worker = 4

[Output]
    # the file path for saving the detected differences on the disk, default is `/tmp/table-diff-{uuid}.diff`
    File = "/tmp/table-diff.diff"
