version: '3.1'

services:
  left-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: leftdb
      MYSQL_ROOT_PASSWORD: password
  right-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 13307:3306
    environment:
      MYSQL_DATABASE: rightdb
      MYSQL_ROOT_PASSWORD: password

